CoffeeShopLab2/Models/UserItems/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShopLab2.Models.UserItems
{
    public class DeleteViewModel
    {
        public int ItemId { get; set; }
        public int UserId { get; set; }

    }
}

CoffeeShopLab2/Models/UserItems/ItemInfoViewModel.cs
using CoffeeShopLab2.Models.CoffeeShop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShopLab2.Models.UserItems
{
    public class ItemInfoViewModel : Item
    {
        public Item AvailableItem { get; set; }
    }
}

CoffeeShopLab2/Models/UserItems/UserPurchasesViewModel.cs
using CoffeeShopLab2.Models.CoffeeShop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShopLab2.Models.UserItems
{
    public class UserPurchasesViewModel
    {
        public List<Item> userPurchases { get; set; }

        public int CurrentUserID { get; set; }

    }
}

CoffeeShopLab2/Controllers/UserItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoffeeShopLab2.DALModels;
using CoffeeShopLab2.Models.CoffeeShop;
using CoffeeShopLab2.Models.UserItems;
using CoffeeShopLab2.Services;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShopLab2.Controllers
{
    public class UserItemsController : Controller
    {
        private readonly ILoggedUser _loggedUser;
        private readonly ShopDBContext _shopDBContext;
        private readonly IUserItems _userItems;

        public UserItemsController(ILoggedUser loggedUser, ShopDBContext shopDBContext, IUserItems userItems)
        {
            _loggedUser = loggedUser;
            _shopDBContext = shopDBContext;
            _userItems = userItems;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ItemDeleted()
        {
            return View();
        }

        public IActionResult AddItem() 
        {

            return View("Shop");
        }

        public IActionResult ItemDetails(int id) 
        {

            var viewModel = new ItemInfoViewModel();

            viewModel.AvailableItem = GetItemWhereIDIsFirst(id);

            return View(viewModel);
        }

        public IActionResult DeleteConfirmation(int id, int userid) 
        {
            var viewModel = new DeleteViewModel();
            viewModel.ItemId = id;
            viewModel.UserId = userid;

            return View(viewModel);
        }

        public IActionResult DeleteItem(int id, int userid) //LAB 24
        {

            var usersItems = _shopDBContext.UserItems.Where(user => user.UserID == _loggedUser.theUser.UserID).ToList();

            foreach (var usersItem in usersItems)
            {
                if (usersItem.ItemID == id)
                {
                    _shopDBContext.UserItems.Remove(usersItem);
                    _shopDBContext.SaveChanges();
                    break;
                }
            }

            return View("ItemDeleted");
        }

        public IActionResult UserPurchases()
        {
            if (_loggedUser.loggedIn == false)
            {

                return View("MustBeLoggedIn");
            }

            var viewModel = new UserPurchasesViewModel();
            viewModel.CurrentUserID = _loggedUser.theUser.UserID;

            var itemIdsOfCurrentUser = _shopDBContext.UserItems.Where(user => user.UserID == viewModel.CurrentUserID).ToList();



            viewModel.userPurchases = itemIdsOfCurrentUser.Select(itemDAL => new Item
            {
                ItemID = itemDAL.ItemID,
                Description = itemDAL.Description,
                Name = itemDAL.Name,
                Price = itemDAL.Price,
                Quantity = itemDAL.Quantity

            }).ToList();


            return View(viewModel);
        }

        private Item GetItemWhereIDIsFirst(int id)
        {
            ItemsDAL itemDAL = _shopDBContext.Items
                .Where(item => item.ItemID == id).FirstOrDefault();

            var item = new Item();
            item.ItemID = itemDAL.ItemID;
            item.Name = itemDAL.Name;
            item.Price = itemDAL.Price;
            item.Description = itemDAL.Description;
            item.Quantity = itemDAL.Quantity;

            return item;
        }


    }
}

CoffeeShopLab2/Views/UserItems/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CoffeeShopLab2.Models.UserItems.DeleteViewModel



<h1> Are you sure you want to delete the selected item ? </h1>


<div><a class="text-success" asp-controller="UserItems" asp-action="DeleteItem" asp-route-id="@Model.ItemId" asp-route-userid="@Model.UserId">YES</a></div>
<div><a class="text-success" asp-controller="UserItems" asp-action="UserPurchases">NO</a></div>

CoffeeShopLab2/Views/UserItems/ItemInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model CoffeeShopLab2.Models.UserItems.ItemInfoViewModel





<h2>PLEASE SEE YOUR ITEM DETAILS BELOW</h2>

<p>Name: @Model.AvailableItem.Name</p>
<p>Description: @Model.AvailableItem.Description</p>
<p>Price: @Model.AvailableItem.Price</p>
<p>Quantity: @Model.AvailableItem.Quantity</p>

CoffeeShopLab2/Views/UserItems/UserPurchases.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model CoffeeShopLab2.Models.UserItems.UserPurchasesViewModel


<link rel="stylesheet" href="~/css/stylesheet.css" type="text/css" />

<h2>Your purchased items are below: </h2>
@{
    foreach (var item in Model.userPurchases)
    {
        <div id="userItems">
            <a asp-controller="UserItems" asp-action="ItemDetails" asp-route-id="@item.ItemID">@item.Name Details</a>
            <br />
            <a asp-controller="UserItems" asp-action="DeleteConfirmation" asp-route-id="@item.ItemID" , asp-route-userid="@Model.CurrentUserID">DELETE ITEM</a>
        </div>
        <br />
    }
}

<h3>Would you like to add any items?</h3>
<a href="/CoffeeShop/Shop">ADD ITEM</a>